### ISSUE TITLE
Keep user conf when upgrading

### ISSUE THREAD

**Issue by Kcchouette** [YunoHost-Apps/jirafeau_ynh#49]
I don't know how is the normal process to upgrade from a version to another for Jirafeau.

But with Yunohost, it seems to overwrite the user config setting (defined in `/var/www/jirafeau/lib/config.local.php`).

I've indeed change the config to change `$cfg['enable_crypt']` from false to true, but when I've done the Jirafeau upgrade, this change has been removed.

Previous version I've had: `3.3.0`, now I have `3.4.1`.

**Comment by maniackcrudelis** [comment]
During the upgrade, you should have seen a warning message saying that your configuration file has been moved to a backup directory, because it was modified since the last upgrade.
So you can always retrieve your own config if you have modified the default one.

But, our process is indeed to overwrite all config files to be sure that there's no conflicts.

**Comment by Kcchouette** [comment]
I'm using the web-ui to do the upgrade so I don't control all the messages that appears…
I didn't know for that, thank you.

**Comment by Jaxom99** [comment]
Hi, thanks for the packaging, I just encountered the same issue.
Maybe there's something to be done about it ? Providing a path to restore settings, or something... Or pointing it out in the README ?

Overwriting the config to default does remove some safety protections (size upload, max duration) and also contact info (in TOS), so it's kind of a big deal !

**Comment by maniackcrudelis** [comment]
Overwritten but kept aside, as a warning should have explained, with the path to the backup.
Path that I couldn't guess since it's built during the backup.

However, a config option is on its way to let admin choose if a config file should be overwritten or not.
Considering though, someone will implement this option in this package. Which is unlikely to happen right now since no one is maintaining this package anymore, as the "Waiting for adoption" state in the readme.

**Comment by Jaxom99** [comment]
Absolutely, we ynh'users should always read all the messages and warning issued :)

Thanks for your reply, ths app is indeed "waiting adoption", but was upgraded nonetheless. So I stay hopeful !
